package com.theredinventor.minerology.init;

import com.theredinventor.minerology.Minerology;
import com.theredinventor.minerology.blocks.*;
import net.minecraft.block.Block;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class MinerologyBlocks {
    public static final DeferredRegister<Block> BLOCKS = new DeferredRegister<>(ForgeRegistries.BLOCKS, Minerology.MOD_ID);
    // Ores
    public static final RegistryObject<Block> Actinium_Ore = BLOCKS.register("actinium_ore", ActiniumOre:: new);
    public static final RegistryObject<Block> Aluminum_Ore = BLOCKS.register("aluminum_ore", AluminumOre:: new);
    public static final RegistryObject<Block> Barium_Ore = BLOCKS.register("barium_ore", BariumOre:: new);
    public static final RegistryObject<Block> Berylium_Ore = BLOCKS.register("berylium_ore", BeryliumOre:: new);
    public static final RegistryObject<Block> Bismuth_Ore = BLOCKS.register("bismuth_ore", BismuthOre:: new);
    public static final RegistryObject<Block> Cadmium_Ore = BLOCKS.register("cadmium_ore", CadmiumOre:: new);
    public static final RegistryObject<Block> Caesium_Ore = BLOCKS.register("caesium_ore", CaesiumOre:: new);
    public static final RegistryObject<Block> Calcium_Ore = BLOCKS.register("calcium_ore", CalciumOre:: new);
    public static final RegistryObject<Block> Cerium_Ore = BLOCKS.register("cerium_ore", CeriumOre:: new);
    public static final RegistryObject<Block> Chromium_Ore = BLOCKS.register("chromium_ore", ChromiumOre:: new);
    public static final RegistryObject<Block> Cobalt_Ore = BLOCKS.register("cobalt_ore", CobaltOre:: new);
    public static final RegistryObject<Block> Copper_Ore = BLOCKS.register("copper_ore", CopperOre:: new);
    public static final RegistryObject<Block> Dysprosium_Ore = BLOCKS.register("dysprosium_ore", DysprosiumOre:: new);
    public static final RegistryObject<Block> Erbium_Ore = BLOCKS.register("erbium_ore", ErbiumOre:: new);
    public static final RegistryObject<Block> Europium_Ore = BLOCKS.register("europium_ore", EuropiumOre:: new);
    public static final RegistryObject<Block> Francium_Ore = BLOCKS.register("francium_ore", FranciumOre:: new);
    public static final RegistryObject<Block> Gadolinium_Ore = BLOCKS.register("gadolinium_ore", GadoliniumOre:: new);
    public static final RegistryObject<Block> Gallium_Ore = BLOCKS.register("gallium_ore", GalliumOre:: new);
    public static final RegistryObject<Block> Hafnium_Ore = BLOCKS.register("hafnium_ore", HafniumOre:: new);
    public static final RegistryObject<Block> Holmium_Ore = BLOCKS.register("holmium_ore", HolmiumOre:: new);
    public static final RegistryObject<Block> Indium_Ore = BLOCKS.register("indium_ore", IndiumOre:: new);
    public static final RegistryObject<Block> Iridium_Ore = BLOCKS.register("iridium_ore", IridiumOre:: new);
    public static final RegistryObject<Block> Lanthanum_Ore = BLOCKS.register("lanthanum_ore", LanthanumOre:: new);
    public static final RegistryObject<Block> Lead_Ore = BLOCKS.register("lead_ore", LeadOre:: new);
    public static final RegistryObject<Block> Lithium_Ore = BLOCKS.register("lithium_ore", LithiumOre:: new);
    public static final RegistryObject<Block> Lutetium_Ore = BLOCKS.register("lutetium_ore", LutetiumOre:: new);
    public static final RegistryObject<Block> Magnesium_Ore = BLOCKS.register("magnesium_ore", MagnesiumOre:: new);
    public static final RegistryObject<Block> Manganese_Ore = BLOCKS.register("manganese_ore", ManganeseOre:: new);
    public static final RegistryObject<Block> Mendelevium_Ore = BLOCKS.register("mendelevium_ore", MendeleviumOre:: new);
    public static final RegistryObject<Block> Mercury_Ore = BLOCKS.register("mercury_ore", MercuryOre:: new);
    public static final RegistryObject<Block> Molybdenum_Ore = BLOCKS.register("molybdenum_ore", MolybdenumOre:: new);
    public static final RegistryObject<Block> Neodymium_Ore = BLOCKS.register("neodymium_ore", MolybdenumOre:: new);
    public static final RegistryObject<Block> Nickel_Ore = BLOCKS.register("nickel_ore", NickelOre:: new);
    public static final RegistryObject<Block> Niobium_Ore = BLOCKS.register("niobium_ore", NiobiumOre:: new);
    public static final RegistryObject<Block> Osmium_Ore = BLOCKS.register("osmium_ore", OsmiumOre:: new);
    public static final RegistryObject<Block> Palladium_Ore = BLOCKS.register("palladium_ore", PalladiumOre:: new);
    public static final RegistryObject<Block> Platinum_Ore = BLOCKS.register("platinum_ore", PlatinumOre:: new);
    public static final RegistryObject<Block> Polonium_Ore = BLOCKS.register("polonium_ore", PoloniumOre:: new);
    public static final RegistryObject<Block> Potassium_Ore = BLOCKS.register("potassium_ore", PotassiumOre:: new);
    public static final RegistryObject<Block> Praseodymium_Ore = BLOCKS.register("praseodymium_ore", PraseodymiumOre:: new);
    public static final RegistryObject<Block> Protactinium_Ore = BLOCKS.register("protactinium_ore", ProtactiniumOre:: new);
    public static final RegistryObject<Block> Radium_Ore = BLOCKS.register("radium_ore", RadiumOre:: new);
    public static final RegistryObject<Block> Rhenium_Ore = BLOCKS.register("rhenium_ore", RheniumOre:: new);
    public static final RegistryObject<Block> Rhodium_Ore = BLOCKS.register("rhodium_ore", RhodiumOre:: new);
    public static final RegistryObject<Block> Rubidium_Ore = BLOCKS.register("rubidium_ore", RubidiumOre:: new);
    public static final RegistryObject<Block> Ruthenium_Ore = BLOCKS.register("ruthenium_ore", RutheniumOre:: new);
    public static final RegistryObject<Block> Samarium_Ore = BLOCKS.register("samarium_ore", SamariumOre:: new);
    public static final RegistryObject<Block> Scandium_Ore = BLOCKS.register("scandium_ore", ScandiumOre:: new);
    public static final RegistryObject<Block> Silicon_Ore = BLOCKS.register("silicon_ore", SiliconOre:: new);
    public static final RegistryObject<Block> Silver_Ore = BLOCKS.register("silver_ore", SilverOre:: new);
    public static final RegistryObject<Block> Sodium_Ore = BLOCKS.register("sodium_ore", SodiumOre:: new);
    public static final RegistryObject<Block> Strontium_Ore = BLOCKS.register("strontium_ore", StrontiumOre:: new);
    public static final RegistryObject<Block> Tantalum_Ore = BLOCKS.register("tantalum_ore", TantalumOre:: new);
    public static final RegistryObject<Block> Terbium_Ore = BLOCKS.register("terbium_ore", TerbiumOre:: new);
    public static final RegistryObject<Block> Thallium_Ore = BLOCKS.register("thallium_ore", ThalliumOre:: new);
    public static final RegistryObject<Block> Thorium_Ore = BLOCKS.register("thorium_ore", ThoriumOre:: new);
    public static final RegistryObject<Block> Thulium_Ore = BLOCKS.register("thulium_ore", ThuliumOre:: new);
    public static final RegistryObject<Block> Tin_Ore = BLOCKS.register("tin_ore", TinOre:: new);
    public static final RegistryObject<Block> Titanium_Ore = BLOCKS.register("titanium_ore", TitaniumOre:: new);
    public static final RegistryObject<Block> Tungsten_Ore = BLOCKS.register("tungsten_ore", TungstenOre:: new);
    public static final RegistryObject<Block> Uranium_Ore = BLOCKS.register("uranium_ore", UraniumOre:: new);
    public static final RegistryObject<Block> Vanadium_Ore = BLOCKS.register("vanadium_ore", VanadiumOre:: new);
    public static final RegistryObject<Block> Ytterbium_Ore = BLOCKS.register("ytterbium_ore", YtterbiumOre:: new);
    public static final RegistryObject<Block> Yttrium_Ore = BLOCKS.register("yttrium_ore", YttriumOre:: new);
    public static final RegistryObject<Block> Zinc_Ore = BLOCKS.register("zinc_ore", ZincOre:: new);
    public static final RegistryObject<Block> Zirconium_Ore = BLOCKS.register("zirconium_ore", ZirconiumOre:: new);
    // Blocks
    public static final RegistryObject<Block> Actinium_Block = BLOCKS.register("actinium_block", ActiniumBlock:: new);
}
