package com.theredinventor.minerology.init;

import com.theredinventor.minerology.Minerology;
import com.theredinventor.minerology.blocks.BlockItemBase;
import com.theredinventor.minerology.items.ItemBase;
import com.theredinventor.minerology.util.enums.MinerologyItemTier;
import net.minecraft.item.Item;
import net.minecraft.item.SwordItem;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class MinerologyItems {
    public static final DeferredRegister<Item> ITEMS = new DeferredRegister<>(ForgeRegistries.ITEMS, Minerology.MOD_ID);
    // Ingots
    public static final RegistryObject<Item> Actinium_Ingot = ITEMS.register( "actinium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Berylium_Ingot = ITEMS.register( "berylium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Aluminum_Ingot = ITEMS.register( "aluminum_ingot", ItemBase::new);
    public static final RegistryObject<Item> Americium_Ingot = ITEMS.register( "americium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Barium_Ingot = ITEMS.register( "barium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Berkelium_Ingot = ITEMS.register( "berkelium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Bismuth_Ingot = ITEMS.register( "bismuth_ingot", ItemBase::new);
    public static final RegistryObject<Item> Bohrium_Ingot = ITEMS.register( "bohrium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Cadmium_Ingot = ITEMS.register( "cadmium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Caesium_Ingot = ITEMS.register( "caesium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Calcium_Ingot = ITEMS.register( "calcium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Californium_Ingot = ITEMS.register( "californium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Cerium_Ingot = ITEMS.register( "cerium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Chromium_Ingot = ITEMS.register( "chromium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Cobalt_Ingot = ITEMS.register( "cobalt_ingot", ItemBase::new);
    public static final RegistryObject<Item> Copernicium_Ingot = ITEMS.register( "copernicium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Copper_Ingot = ITEMS.register( "copper_ingot", ItemBase::new);
    public static final RegistryObject<Item> Curium_Ingot = ITEMS.register( "curium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Darmstadium_Ingot = ITEMS.register( "darmstadtium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Dubnium_Ingot = ITEMS.register( "dubnium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Dysprosium_Ingot = ITEMS.register( "dysprosium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Einsteinium_Ingot = ITEMS.register( "einsteinium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Erbium_Ingot = ITEMS.register( "erbium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Europium_Ingot = ITEMS.register( "europium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Fermium_Ingot = ITEMS.register( "fermium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Flerovium_Ingot = ITEMS.register( "flerovium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Francium_Ingot = ITEMS.register( "francium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Gadolinium_Ingot = ITEMS.register( "gadolinium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Gallium_Ingot = ITEMS.register( "gallium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Hafnium_Ingot = ITEMS.register( "hafnium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Hassium_Ingot = ITEMS.register( "hassium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Holmium_Ingot = ITEMS.register( "holmium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Indium_Ingot = ITEMS.register( "indium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Iridium_Ingot = ITEMS.register( "iridium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Lanthanum_Ingot = ITEMS.register( "lanthanum_ingot", ItemBase::new);
    public static final RegistryObject<Item> Lawrencium_Ingot = ITEMS.register( "lawrencium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Lead_Ingot = ITEMS.register( "lead_ingot", ItemBase::new);
    public static final RegistryObject<Item> Lithium_Ingot = ITEMS.register( "lithium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Livermorium_Ingot = ITEMS.register( "livermorium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Lutetium_Ingot = ITEMS.register( "lutetium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Magnesium_Ingot = ITEMS.register( "magnesium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Manganese_Ingot = ITEMS.register( "manganese_ingot", ItemBase::new);
    public static final RegistryObject<Item> Meitnerium_Ingot = ITEMS.register( "meitnerium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Mendelevium_Ingot = ITEMS.register( "mendelevium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Mercury_Ingot = ITEMS.register( "mercury_ingot", ItemBase::new);
    public static final RegistryObject<Item> Molybdenum_Ingot = ITEMS.register("molybdenum_ingot", ItemBase::new);
    public static final RegistryObject<Item> Moscovium_Ingot = ITEMS.register("moscovium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Neodymium_Ingot = ITEMS.register("neodymium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Neptunium_Ingot = ITEMS.register("neptunium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Nickel_Ingot = ITEMS.register("nickel_ingot", ItemBase::new);
    public static final RegistryObject<Item> Nihonium_Ingot = ITEMS.register("nihonium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Niobium_Ingot = ITEMS.register("niobium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Nobelium_Ingot = ITEMS.register("nobelium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Oganesson_Ingot = ITEMS.register("oganesson_ingot", ItemBase::new);
    public static final RegistryObject<Item> Osmium_Ingot = ITEMS.register("osmium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Palladium_Ingot = ITEMS.register("palladium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Platinum_Ingot = ITEMS.register("platinum_ingot", ItemBase::new);
    public static final RegistryObject<Item> Plutonium_Ingot = ITEMS.register("plutonium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Polonium_Ingot = ITEMS.register("polonium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Potassium_Ingot = ITEMS.register("potassium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Praseodymium_Ingot = ITEMS.register("praseodymium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Promethium_Ingot = ITEMS.register("promethium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Protactinium_Ingot = ITEMS.register("protactinium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Radium_Ingot = ITEMS.register("radium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Rhenium_Ingot = ITEMS.register("rhenium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Rhodium_Ingot = ITEMS.register("rhodium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Roentgenium_Ingot = ITEMS.register("roentgenium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Rubidium_Ingot = ITEMS.register("rubidium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Ruthenium_Ingot = ITEMS.register("ruthenium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Rutherfordium_Ingot = ITEMS.register("rutherfordium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Samarium_Ingot = ITEMS.register("samarium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Scandium_Ingot = ITEMS.register("scandium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Seaborgium_Ingot = ITEMS.register("seaborgium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Silicon = ITEMS.register("silicon", ItemBase::new);
    public static final RegistryObject<Item> Silver_Ingot = ITEMS.register("silver_ingot", ItemBase::new);
    public static final RegistryObject<Item> Sodium = ITEMS.register("sodium", ItemBase::new);
    public static final RegistryObject<Item> Strontium_Ingot = ITEMS.register("strontium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Tantalum_Ingot = ITEMS.register("tantalum_ingot", ItemBase::new);
    public static final RegistryObject<Item> Technetium_Ingot = ITEMS.register("technetium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Tennessine_Ingot = ITEMS.register("tennessine_ingot", ItemBase::new);
    public static final RegistryObject<Item> Terbium_Ingot = ITEMS.register("terbium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Thallium_Ingot = ITEMS.register("thallium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Thorium_Ingot = ITEMS.register("thorium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Thulium_Ingot = ITEMS.register("thulium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Tin_Ingot = ITEMS.register("tin_ingot", ItemBase::new);
    public static final RegistryObject<Item> Titanium_Ingot = ITEMS.register("titanium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Tungsten_Ingot = ITEMS.register("tungsten_ingot", ItemBase::new);
    public static final RegistryObject<Item> Uranium_Ingot = ITEMS.register("uranium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Vanadium_Ingot = ITEMS.register("vanadium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Ytterbium_Ingot = ITEMS.register("ytterbium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Yttrium_Ingot = ITEMS.register("yttrium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Zinc_Ingot = ITEMS.register("zinc_ingot", ItemBase::new);
    public static final RegistryObject<Item> Zirconium_Ingot = ITEMS.register("zirconium_ingot", ItemBase::new);
    // Ores Items
    public static final RegistryObject<Item> Actinium_Ore_Item = ITEMS.register("actinium_ore", () -> new BlockItemBase(MinerologyBlocks.Actinium_Ore.get()));
    public static final RegistryObject<Item> Aluminum_Ore_Item = ITEMS.register("aluminum_ore", () -> new BlockItemBase(MinerologyBlocks.Aluminum_Ore.get()));
    public static final RegistryObject<Item> Barium_Ore_Item = ITEMS.register("barium_ore", () -> new BlockItemBase(MinerologyBlocks.Barium_Ore.get()));
    public static final RegistryObject<Item> Berylium_Ore_Item = ITEMS.register("berylium_ore", () -> new BlockItemBase(MinerologyBlocks.Berylium_Ore.get()));
    public static final RegistryObject<Item> Bismuth_Ore_Item = ITEMS.register("bismuth_ore", () -> new BlockItemBase(MinerologyBlocks.Bismuth_Ore.get()));
    public static final RegistryObject<Item> Cadmium_Ore_Item = ITEMS.register("cadmium_ore", () -> new BlockItemBase(MinerologyBlocks.Cadmium_Ore.get()));
    public static final RegistryObject<Item> Calcium_Ore_Item = ITEMS.register("calcium_ore", () -> new BlockItemBase(MinerologyBlocks.Calcium_Ore.get()));
    public static final RegistryObject<Item> Cerium_Ore_Item = ITEMS.register("cerium_ore", () -> new BlockItemBase(MinerologyBlocks.Cerium_Ore.get()));
    public static final RegistryObject<Item> Caesium_Ore_Item = ITEMS.register("caesium_ore", () -> new BlockItemBase(MinerologyBlocks.Caesium_Ore.get()));
    public static final RegistryObject<Item> Chromium_Ore_Item = ITEMS.register("chromium_ore", () -> new BlockItemBase(MinerologyBlocks.Chromium_Ore.get()));
    public static final RegistryObject<Item> Cobalt_Ore_Item = ITEMS.register("cobalt_ore", () -> new BlockItemBase(MinerologyBlocks.Cobalt_Ore.get()));
    public static final RegistryObject<Item> Copper_Ore_Item = ITEMS.register("copper_ore", () -> new BlockItemBase(MinerologyBlocks.Copper_Ore.get()));
    public static final RegistryObject<Item> Dysprosium_Ore_Item = ITEMS.register("dysprosium_ore", () -> new BlockItemBase(MinerologyBlocks.Dysprosium_Ore.get()));
    public static final RegistryObject<Item> Erbium_Ore_Item = ITEMS.register("erbium_ore", () -> new BlockItemBase(MinerologyBlocks.Erbium_Ore.get()));
    public static final RegistryObject<Item> Europium_Ore_Item = ITEMS.register("europium_ore", () -> new BlockItemBase(MinerologyBlocks.Europium_Ore.get()));
    public static final RegistryObject<Item> Francium_Ore_Item = ITEMS.register("francium_ore", () -> new BlockItemBase(MinerologyBlocks.Francium_Ore.get()));
    public static final RegistryObject<Item> Gadolinium_Ore_Item = ITEMS.register("gadolinium_ore", () -> new BlockItemBase(MinerologyBlocks.Gadolinium_Ore.get()));
    public static final RegistryObject<Item> Gallium_Ore_Item = ITEMS.register("gallium_ore", () -> new BlockItemBase(MinerologyBlocks.Gallium_Ore.get()));
    public static final RegistryObject<Item> Hafnium_Ore_Item = ITEMS.register("hafnium_ore", () -> new BlockItemBase(MinerologyBlocks.Hafnium_Ore.get()));
    public static final RegistryObject<Item> Holmium_Ore_Item = ITEMS.register("holmium_ore", () -> new BlockItemBase(MinerologyBlocks.Holmium_Ore.get()));
    public static final RegistryObject<Item> Indium_Ore_Item = ITEMS.register("indium_ore", () -> new BlockItemBase(MinerologyBlocks.Indium_Ore.get()));
    public static final RegistryObject<Item> Iridium_Ore_Item = ITEMS.register("iridium_ore", () -> new BlockItemBase(MinerologyBlocks.Iridium_Ore.get()));
    public static final RegistryObject<Item> Lanthanum_Ore_Item = ITEMS.register("lanthanum_ore", () -> new BlockItemBase(MinerologyBlocks.Lanthanum_Ore.get()));
    public static final RegistryObject<Item> Lead_Ore_Item = ITEMS.register("lead_ore", () -> new BlockItemBase(MinerologyBlocks.Lead_Ore.get()));
    public static final RegistryObject<Item> Lithium_Ore_Item = ITEMS.register("lithium_ore", () -> new BlockItemBase(MinerologyBlocks.Lithium_Ore.get()));
    public static final RegistryObject<Item> Lutetium_Ore_Item = ITEMS.register("lutetium_ore", () -> new BlockItemBase(MinerologyBlocks.Lutetium_Ore.get()));
    public static final RegistryObject<Item> Magnesium_Ore_Item = ITEMS.register("magnesium_ore", () -> new BlockItemBase(MinerologyBlocks.Magnesium_Ore.get()));
    public static final RegistryObject<Item> Manganese_Ore_Item = ITEMS.register("manganese_ore", () -> new BlockItemBase(MinerologyBlocks.Manganese_Ore.get()));
    public static final RegistryObject<Item> Mendelevium_Ore_Item = ITEMS.register("mendelevium_ore", () -> new BlockItemBase(MinerologyBlocks.Mendelevium_Ore.get()));
    public static final RegistryObject<Item> Mercury_Ore_Item = ITEMS.register("mercury_ore", () -> new BlockItemBase(MinerologyBlocks.Mercury_Ore.get()));
    public static final RegistryObject<Item> Molybdenum_Ore_Item = ITEMS.register("molybdenum_ore", () -> new BlockItemBase(MinerologyBlocks.Molybdenum_Ore.get()));
    public static final RegistryObject<Item> Neodymium_Ore_Item = ITEMS.register("neodymium_ore", () -> new BlockItemBase(MinerologyBlocks.Neodymium_Ore.get()));
    public static final RegistryObject<Item> Nickel_Ore_Item = ITEMS.register("nickel_ore", () -> new BlockItemBase(MinerologyBlocks.Nickel_Ore.get()));
    public static final RegistryObject<Item> Niobium_Ore_Item = ITEMS.register("niobium_ore", () -> new BlockItemBase(MinerologyBlocks.Niobium_Ore.get()));
    public static final RegistryObject<Item> Osmium_Ore_Item = ITEMS.register("osmium_ore", () -> new BlockItemBase(MinerologyBlocks.Osmium_Ore.get()));
    public static final RegistryObject<Item> Palladium_Ore_Item = ITEMS.register("palladium_ore", () -> new BlockItemBase(MinerologyBlocks.Palladium_Ore.get()));
    public static final RegistryObject<Item> Platinium_Ore_Item = ITEMS.register("platinum_ore", () -> new BlockItemBase(MinerologyBlocks.Platinum_Ore.get()));
    public static final RegistryObject<Item> Polonium_Ore_Item = ITEMS.register("polonium_ore", () -> new BlockItemBase(MinerologyBlocks.Polonium_Ore.get()));
    public static final RegistryObject<Item> Potassium_Ore_Item = ITEMS.register("potassium_ore", () -> new BlockItemBase(MinerologyBlocks.Potassium_Ore.get()));
    public static final RegistryObject<Item> Praseodymium_Ore_Item = ITEMS.register("praseodymium_ore", () -> new BlockItemBase(MinerologyBlocks.Praseodymium_Ore.get()));
    public static final RegistryObject<Item> Protactinium_Ore_Item = ITEMS.register("protactinium_ore", () -> new BlockItemBase(MinerologyBlocks.Protactinium_Ore.get()));
    public static final RegistryObject<Item> Radium_Ore_Item = ITEMS.register("radium_ore", () -> new BlockItemBase(MinerologyBlocks.Radium_Ore.get()));
    public static final RegistryObject<Item> Rhenium_Ore_Item = ITEMS.register("rhenium_ore", () -> new BlockItemBase(MinerologyBlocks.Rhenium_Ore.get()));
    public static final RegistryObject<Item> Rhodium_Ore_Item = ITEMS.register("rhodium_ore", () -> new BlockItemBase(MinerologyBlocks.Rhodium_Ore.get()));
    public static final RegistryObject<Item> Rubidium_Ore_Item = ITEMS.register("rubidium_ore", () -> new BlockItemBase(MinerologyBlocks.Rubidium_Ore.get()));
    public static final RegistryObject<Item> Ruthenium_Ore_Item = ITEMS.register("ruthenium_ore", () -> new BlockItemBase(MinerologyBlocks.Ruthenium_Ore.get()));
    public static final RegistryObject<Item> Samarium_Ore_Item = ITEMS.register("samarium_ore", () -> new BlockItemBase(MinerologyBlocks.Samarium_Ore.get()));
    public static final RegistryObject<Item> Scandium_Ore_Item = ITEMS.register("scandium_ore", () -> new BlockItemBase(MinerologyBlocks.Scandium_Ore.get()));
    public static final RegistryObject<Item> Silicon_Ore_Item = ITEMS.register("silicon_ore", () -> new BlockItemBase(MinerologyBlocks.Silicon_Ore.get()));
    public static final RegistryObject<Item> Silver_Ore_Item = ITEMS.register("silver_ore", () -> new BlockItemBase(MinerologyBlocks.Silver_Ore.get()));
    public static final RegistryObject<Item> Sodium_Ore_Item = ITEMS.register("sodium_ore", () -> new BlockItemBase(MinerologyBlocks.Sodium_Ore.get()));
    public static final RegistryObject<Item> Strontium_Ore_Item = ITEMS.register("strontium_ore", () -> new BlockItemBase(MinerologyBlocks.Strontium_Ore.get()));
    public static final RegistryObject<Item> Tantalum_Ore_Item = ITEMS.register("tantalum_ore", () -> new BlockItemBase(MinerologyBlocks.Tantalum_Ore.get()));
    public static final RegistryObject<Item> Terbium_Ore_Item = ITEMS.register("terbium_ore", () -> new BlockItemBase(MinerologyBlocks.Terbium_Ore.get()));
    public static final RegistryObject<Item> Thallium_Ore_Item = ITEMS.register("thallium_ore", () -> new BlockItemBase(MinerologyBlocks.Thallium_Ore.get()));
    public static final RegistryObject<Item> Thorium_Ore_Item = ITEMS.register("thorium_ore", () -> new BlockItemBase(MinerologyBlocks.Thorium_Ore.get()));
    public static final RegistryObject<Item> Thulium_Ore_Item = ITEMS.register("thulium_ore", () -> new BlockItemBase(MinerologyBlocks.Thulium_Ore.get()));
    public static final RegistryObject<Item> Tin_Ore_Item = ITEMS.register("tin_ore", () -> new BlockItemBase(MinerologyBlocks.Tin_Ore.get()));
    public static final RegistryObject<Item> Titanium_Ore_Item = ITEMS.register("titanium_ore", () -> new BlockItemBase(MinerologyBlocks.Titanium_Ore.get()));
    public static final RegistryObject<Item> Tungsten_Ore_Item = ITEMS.register("tungsten_ore", () -> new BlockItemBase(MinerologyBlocks.Tungsten_Ore.get()));
    public static final RegistryObject<Item> Uranium_Ore_Item = ITEMS.register("uranium_ore", () -> new BlockItemBase(MinerologyBlocks.Uranium_Ore.get()));
    public static final RegistryObject<Item> Vanadium_Ore_Item = ITEMS.register("vanadium_ore", () -> new BlockItemBase(MinerologyBlocks.Vanadium_Ore.get()));
    public static final RegistryObject<Item> Ytterbium_Ore_Item = ITEMS.register("ytterbium_ore", () -> new BlockItemBase(MinerologyBlocks.Ytterbium_Ore.get()));
    public static final RegistryObject<Item> Yttrium_Ore_Item = ITEMS.register("yttrium_ore", () -> new BlockItemBase(MinerologyBlocks.Yttrium_Ore.get()));
    public static final RegistryObject<Item> Zinc_Ore_Item = ITEMS.register("zinc_ore", () -> new BlockItemBase(MinerologyBlocks.Zinc_Ore.get()));
    public static final RegistryObject<Item> ZirconiumOre_Item = ITEMS.register("zirconium_ore", () -> new BlockItemBase(MinerologyBlocks.Zirconium_Ore.get()));
    // Block Items
    public static final RegistryObject<Item> Actinium_Block_Item = ITEMS.register("actinium_block", () -> new BlockItemBase(MinerologyBlocks.Actinium_Block.get()));
    // Tools
    public  static final RegistryObject<Item> Aluminum_Sword = ITEMS.register("aluminum_sword", () ->
            new SwordItem(MinerologyItemTier.ALUMINUM, 3, -2.4F, new Item.Properties().group(Minerology.TAB)));

}
