package com.theredinventor.minerology.util;

import com.theredinventor.minerology.Minerology;
import com.theredinventor.minerology.blocks.*;
import com.theredinventor.minerology.items.ItemBase;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class RegistryHandler {

    public static final DeferredRegister<Item> ITEMS = new DeferredRegister<>(ForgeRegistries.ITEMS, Minerology.MOD_ID);
    public static final DeferredRegister<Block> BLOCKS = new DeferredRegister<>(ForgeRegistries.BLOCKS, Minerology.MOD_ID);

    public static void init(){
        ITEMS.register(FMLJavaModLoadingContext.get().getModEventBus());
        BLOCKS.register(FMLJavaModLoadingContext.get().getModEventBus());
    }
    // Items
    public static final RegistryObject<Item> Actinium_Ingot = ITEMS.register( "actinium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Berylium_Ingot = ITEMS.register( "berylium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Aluminum_Ingot = ITEMS.register( "aluminum_ingot", ItemBase::new);
    public static final RegistryObject<Item> Americium_Ingot = ITEMS.register( "americium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Barium_Ingot = ITEMS.register( "barium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Berkelium_Ingot = ITEMS.register( "berkelium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Bismuth_Ingot = ITEMS.register( "bismuth_ingot", ItemBase::new);
    public static final RegistryObject<Item> Bohrium_Ingot = ITEMS.register( "bohrium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Cadmium_Ingot = ITEMS.register( "cadmium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Caesium_Ingot = ITEMS.register( "caesium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Calcium_Ingot = ITEMS.register( "calcium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Californium_Ingot = ITEMS.register( "californium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Cerium_Ingot = ITEMS.register( "cerium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Chromium_Ingot = ITEMS.register( "chromium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Cobalt_Ingot = ITEMS.register( "cobalt_ingot", ItemBase::new);
    public static final RegistryObject<Item> Copernicium_Ingot = ITEMS.register( "copernicium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Copper_Ingot = ITEMS.register( "copper_ingot", ItemBase::new);
    public static final RegistryObject<Item> Curium_Ingot = ITEMS.register( "curium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Darmstadium_Ingot = ITEMS.register( "darmstadtium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Dubnium_Ingot = ITEMS.register( "dubnium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Dysprosium_Ingot = ITEMS.register( "dysprosium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Einsteinium_Ingot = ITEMS.register( "einsteinium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Erbium_Ingot = ITEMS.register( "erbium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Europium_Ingot = ITEMS.register( "europium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Fermium_Ingot = ITEMS.register( "fermium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Flerovium_Ingot = ITEMS.register( "flerovium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Francium_Ingot = ITEMS.register( "francium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Gadolinium_Ingot = ITEMS.register( "gadolinium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Gallium_Ingot = ITEMS.register( "gallium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Hafnium_Ingot = ITEMS.register( "hafnium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Hassium_Ingot = ITEMS.register( "hassium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Holmium_Ingot = ITEMS.register( "holmium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Indium_Ingot = ITEMS.register( "indium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Iridium_Ingot = ITEMS.register( "iridium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Lanthanum_Ingot = ITEMS.register( "lanthanum_ingot", ItemBase::new);
    public static final RegistryObject<Item> Lawrencium_Ingot = ITEMS.register( "lawrencium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Lead_Ingot = ITEMS.register( "lead_ingot", ItemBase::new);
    public static final RegistryObject<Item> Lithium_Ingot = ITEMS.register( "lithium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Livermorium_Ingot = ITEMS.register( "livermorium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Lutetium_Ingot = ITEMS.register( "lutetium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Magnesium_Ingot = ITEMS.register( "magnesium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Manganese_Ingot = ITEMS.register( "manganese_ingot", ItemBase::new);
    public static final RegistryObject<Item> Meitnerium_Ingot = ITEMS.register( "meitnerium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Mendelevium_Ingot = ITEMS.register( "mendelevium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Mercury_Ingot = ITEMS.register( "mercury_ingot", ItemBase::new);  
    public static final RegistryObject<Item> Molybdenum_Ingot = ITEMS.register("molybdenum_ingot", ItemBase::new);
    public static final RegistryObject<Item> Moscovium_Ingot = ITEMS.register("moscovium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Neodymium_Ingot = ITEMS.register("neodymium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Neptunium_Ingot = ITEMS.register("neptunium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Nickel_Ingot = ITEMS.register("nickel_ingot", ItemBase::new);
    public static final RegistryObject<Item> Nihonium_Ingot = ITEMS.register("nihonium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Niobium_Ingot = ITEMS.register("niobium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Nobelium_Ingot = ITEMS.register("nobelium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Oganesson_Ingot = ITEMS.register("oganesson_ingot", ItemBase::new);
    public static final RegistryObject<Item> Osmium_Ingot = ITEMS.register("osmium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Palladium_Ingot = ITEMS.register("palladium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Platinum_Ingot = ITEMS.register("platinum_ingot", ItemBase::new);
    public static final RegistryObject<Item> Plutonium_Ingot = ITEMS.register("plutonium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Polonium_Ingot = ITEMS.register("polonium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Potassium_Ingot = ITEMS.register("potassium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Praseodymium_Ingot = ITEMS.register("praseodymium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Promethium_Ingot = ITEMS.register("promethium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Protactinium_Ingot = ITEMS.register("protactinium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Radium_Ingot = ITEMS.register("radium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Rhenium_Ingot = ITEMS.register("rhenium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Rhodium_Ingot = ITEMS.register("rhodium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Roentgenium_Ingot = ITEMS.register("roentgenium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Rubidium_Ingot = ITEMS.register("rubidium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Ruthenium_Ingot = ITEMS.register("ruthenium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Rutherfordium_Ingot = ITEMS.register("rutherfordium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Samarium_Ingot = ITEMS.register("samarium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Scandium_Ingot = ITEMS.register("scandium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Seaborgium_Ingot = ITEMS.register("seaborgium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Silicon = ITEMS.register("silicon", ItemBase::new);
    public static final RegistryObject<Item> Silver_Ingot = ITEMS.register("silver_ingot", ItemBase::new);
    public static final RegistryObject<Item> Sodium = ITEMS.register("sodium", ItemBase::new);
    public static final RegistryObject<Item> Strontium_Ingot = ITEMS.register("strontium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Tantalum_Ingot = ITEMS.register("tantalum_ingot", ItemBase::new);
    public static final RegistryObject<Item> Technetium_Ingot = ITEMS.register("technetium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Tennessine_Ingot = ITEMS.register("tennessine_ingot", ItemBase::new);
    public static final RegistryObject<Item> Terbium_Ingot = ITEMS.register("terbium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Thallium_Ingot = ITEMS.register("thallium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Thorium_Ingot = ITEMS.register("thorium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Thulium_Ingot = ITEMS.register("thulium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Tin_Ingot = ITEMS.register("tin_ingot", ItemBase::new);
    public static final RegistryObject<Item> Titanium_Ingot = ITEMS.register("titanium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Tungsten_Ingot = ITEMS.register("tungsten_ingot", ItemBase::new);
    public static final RegistryObject<Item> Uranium_Ingot = ITEMS.register("uranium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Vanadium_Ingot = ITEMS.register("vanadium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Ytterbium_Ingot = ITEMS.register("ytterbium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Yttrium_Ingot = ITEMS.register("yttrium_ingot", ItemBase::new);
    public static final RegistryObject<Item> Zinc_Ingot = ITEMS.register("zinc_ingot", ItemBase::new);
    public static final RegistryObject<Item> Zirconium_Ingot = ITEMS.register("zirconium_ingot", ItemBase::new);

    // Ores
    public static final RegistryObject<Block> Actinium_Ore = BLOCKS.register("actinium_ore", ActiniumOre:: new);
    public static final RegistryObject<Block> Aluminum_Ore = BLOCKS.register("aluminum_ore", AluminumOre:: new);
    public static final RegistryObject<Block> Barium_Ore = BLOCKS.register("barium_ore", BariumOre:: new);
    public static final RegistryObject<Block> Berylium_Ore = BLOCKS.register("berylium_ore", BeryliumOre:: new);
    public static final RegistryObject<Block> Bismuth_Ore = BLOCKS.register("bismuth_ore", BismuthOre:: new);
    public static final RegistryObject<Block> Cadmium_Ore = BLOCKS.register("cadmium_ore", CadmiumOre:: new);
    public static final RegistryObject<Block> Caesium_Ore = BLOCKS.register("caesium_ore", CaesiumOre:: new);
    public static final RegistryObject<Block> Calcium_Ore = BLOCKS.register("calcium_ore", CalciumOre:: new);
    public static final RegistryObject<Block> Cerium_Ore = BLOCKS.register("cerium_ore", CeriumOre:: new);
    public static final RegistryObject<Block> Chromium_Ore = BLOCKS.register("chromium_ore", ChromiumOre:: new);
    public static final RegistryObject<Block> Cobalt_Ore = BLOCKS.register("cobalt_ore", CobaltOre:: new);
    public static final RegistryObject<Block> Copper_Ore = BLOCKS.register("copper_ore", CopperOre:: new);
    public static final RegistryObject<Block> Dysprosium_Ore = BLOCKS.register("dysprosium_ore", DysprosiumOre:: new);
    public static final RegistryObject<Block> Erbium_Ore = BLOCKS.register("erbium_ore", ErbiumOre:: new);
    public static final RegistryObject<Block> Europium_Ore = BLOCKS.register("europium_ore", EuropiumOre:: new);
    public static final RegistryObject<Block> Francium_Ore = BLOCKS.register("francium_ore", FranciumOre:: new);
    public static final RegistryObject<Block> Gadolinium_Ore = BLOCKS.register("gadolinium_ore", GadoliniumOre:: new);
    public static final RegistryObject<Block> Gallium_Ore = BLOCKS.register("gallium_ore", GalliumOre:: new);
    public static final RegistryObject<Block> Hafnium_Ore = BLOCKS.register("hafnium_ore", HafniumOre:: new);
    public static final RegistryObject<Block> Holmium_Ore = BLOCKS.register("holmium_ore", HolmiumOre:: new);
    public static final RegistryObject<Block> Indium_Ore = BLOCKS.register("indium_ore", IndiumOre:: new);
    public static final RegistryObject<Block> Iridium_Ore = BLOCKS.register("iridium_ore", IridiumOre:: new);
    public static final RegistryObject<Block> Lanthanum_Ore = BLOCKS.register("lanthanum_ore", LanthanumOre:: new);
    public static final RegistryObject<Block> Lead_Ore = BLOCKS.register("lead_ore", LeadOre:: new);
    public static final RegistryObject<Block> Lithium_Ore = BLOCKS.register("lithium_ore", LithiumOre:: new);
    public static final RegistryObject<Block> Lutetium_Ore = BLOCKS.register("lutetium_ore", LutetiumOre:: new);
    public static final RegistryObject<Block> Magnesium_Ore = BLOCKS.register("magnesium_ore", MagnesiumOre:: new);
    public static final RegistryObject<Block> Manganese_Ore = BLOCKS.register("manganese_ore", ManganeseOre:: new);
    public static final RegistryObject<Block> Mendelevium_Ore = BLOCKS.register("mendelevium_ore", MendeleviumOre:: new);
    public static final RegistryObject<Block> Mercury_Ore = BLOCKS.register("mercury_ore", MercuryOre:: new);
    public static final RegistryObject<Block> Molybdenum_Ore = BLOCKS.register("molybdenum_ore", MolybdenumOre:: new);
    public static final RegistryObject<Block> Neodymium_Ore = BLOCKS.register("neodymium_ore", MolybdenumOre:: new);
    public static final RegistryObject<Block> Nickel_Ore = BLOCKS.register("nickel_ore", NickelOre:: new);
    public static final RegistryObject<Block> Niobium_Ore = BLOCKS.register("niobium_ore", NiobiumOre:: new);
    public static final RegistryObject<Block> Osmium_Ore = BLOCKS.register("osmium_ore", OsmiumOre:: new);
    public static final RegistryObject<Block> Palladium_Ore = BLOCKS.register("palladium_ore", PalladiumOre:: new);
    public static final RegistryObject<Block> Platinum_Ore = BLOCKS.register("platinum_ore", PlatinumOre:: new);
    public static final RegistryObject<Block> Polonium_Ore = BLOCKS.register("polonium_ore", PoloniumOre:: new);
    public static final RegistryObject<Block> Potassium_Ore = BLOCKS.register("potassium_ore", PotassiumOre:: new);
    public static final RegistryObject<Block> Praseodymium_Ore = BLOCKS.register("praseodymium_ore", PraseodymiumOre:: new);
    public static final RegistryObject<Block> Protactinium_Ore = BLOCKS.register("protactinium_ore", ProtactiniumOre:: new);
    public static final RegistryObject<Block> Radium_Ore = BLOCKS.register("radium_ore", RadiumOre:: new);
    public static final RegistryObject<Block> Rhenium_Ore = BLOCKS.register("rhenium_ore", RheniumOre:: new);
    public static final RegistryObject<Block> Rhodium_Ore = BLOCKS.register("rhodium_ore", RhodiumOre:: new);
    public static final RegistryObject<Block> Rubidium_Ore = BLOCKS.register("rubidium_ore", RubidiumOre:: new);
    public static final RegistryObject<Block> Ruthenium_Ore = BLOCKS.register("ruthenium_ore", RutheniumOre:: new);
    public static final RegistryObject<Block> Samarium_Ore = BLOCKS.register("samarium_ore", SamariumOre:: new);
    public static final RegistryObject<Block> Scandium_Ore = BLOCKS.register("scandium_ore", ScandiumOre:: new);
    public static final RegistryObject<Block> Silicon_Ore = BLOCKS.register("silicon_ore", SiliconOre:: new);
    public static final RegistryObject<Block> Silver_Ore = BLOCKS.register("silver_ore", SilverOre:: new);
    public static final RegistryObject<Block> Sodium_Ore = BLOCKS.register("sodium_ore", SodiumOre:: new);
    public static final RegistryObject<Block> Strontium_Ore = BLOCKS.register("strontium_ore", StrontiumOre:: new);
    public static final RegistryObject<Block> Tantalum_Ore = BLOCKS.register("tantalum_ore", TantalumOre:: new);
    public static final RegistryObject<Block> Terbium_Ore = BLOCKS.register("terbium_ore", TerbiumOre:: new);
    public static final RegistryObject<Block> Thallium_Ore = BLOCKS.register("thallium_ore", ThalliumOre:: new);
    public static final RegistryObject<Block> Thorium_Ore = BLOCKS.register("thorium_ore", ThoriumOre:: new);
    public static final RegistryObject<Block> Thulium_Ore = BLOCKS.register("thulium_ore", ThuliumOre:: new);
    public static final RegistryObject<Block> Tin_Ore = BLOCKS.register("tin_ore", TinOre:: new);
    public static final RegistryObject<Block> Titanium_Ore = BLOCKS.register("titanium_ore", TitaniumOre:: new);
    public static final RegistryObject<Block> Tungsten_Ore = BLOCKS.register("tungsten_ore", TungstenOre:: new);
    public static final RegistryObject<Block> Uranium_Ore = BLOCKS.register("uranium_ore", UraniumOre:: new);
    public static final RegistryObject<Block> Vanadium_Ore = BLOCKS.register("vanadium_ore", VanadiumOre:: new);
    public static final RegistryObject<Block> Ytterbium_Ore = BLOCKS.register("ytterbium_ore", YtterbiumOre:: new);
    public static final RegistryObject<Block> Yttrium_Ore = BLOCKS.register("yttrium_ore", YttriumOre:: new);
    public static final RegistryObject<Block> Zinc_Ore = BLOCKS.register("zinc_ore", ZincOre:: new);
    public static final RegistryObject<Block> Zirconium_Ore = BLOCKS.register("zirconium_ore", ZirconiumOre:: new);

    // Ores Items
    public static final RegistryObject<Item> Actinium_Ore_Item = ITEMS.register("actinium_ore", () -> new BlockItemBase(Actinium_Ore.get()));
    public static final RegistryObject<Item> Aluminum_Ore_Item = ITEMS.register("aluminum_ore", () -> new BlockItemBase(Aluminum_Ore.get()));
    public static final RegistryObject<Item> Barium_Ore_Item = ITEMS.register("barium_ore", () -> new BlockItemBase(Barium_Ore.get()));
    public static final RegistryObject<Item> Berylium_Ore_Item = ITEMS.register("berylium_ore", () -> new BlockItemBase(Berylium_Ore.get()));
    public static final RegistryObject<Item> Bismuth_Ore_Item = ITEMS.register("bismuth_ore", () -> new BlockItemBase(Bismuth_Ore.get()));
    public static final RegistryObject<Item> Cadmium_Ore_Item = ITEMS.register("cadmium_ore", () -> new BlockItemBase(Cadmium_Ore.get()));
    public static final RegistryObject<Item> Calcium_Ore_Item = ITEMS.register("calcium_ore", () -> new BlockItemBase(Calcium_Ore.get()));
    public static final RegistryObject<Item> Cerium_Ore_Item = ITEMS.register("cerium_ore", () -> new BlockItemBase(Cerium_Ore.get()));
    public static final RegistryObject<Item> Caesium_Ore_Item = ITEMS.register("caesium_ore", () -> new BlockItemBase(Caesium_Ore.get()));
    public static final RegistryObject<Item> Chromium_Ore_Item = ITEMS.register("chromium_ore", () -> new BlockItemBase(Chromium_Ore.get()));
    public static final RegistryObject<Item> Cobalt_Ore_Item = ITEMS.register("cobalt_ore", () -> new BlockItemBase(Cobalt_Ore.get()));
    public static final RegistryObject<Item> Copper_Ore_Item = ITEMS.register("copper_ore", () -> new BlockItemBase(Copper_Ore.get()));
    public static final RegistryObject<Item> Dysprosium_Ore_Item = ITEMS.register("dysprosium_ore", () -> new BlockItemBase(Dysprosium_Ore.get()));
    public static final RegistryObject<Item> Erbium_Ore_Item = ITEMS.register("erbium_ore", () -> new BlockItemBase(Erbium_Ore.get()));
    public static final RegistryObject<Item> Europium_Ore_Item = ITEMS.register("europium_ore", () -> new BlockItemBase(Europium_Ore.get()));
    public static final RegistryObject<Item> Francium_Ore_Item = ITEMS.register("francium_ore", () -> new BlockItemBase(Francium_Ore.get()));
    public static final RegistryObject<Item> Gadolinium_Ore_Item = ITEMS.register("gadolinium_ore", () -> new BlockItemBase(Gadolinium_Ore.get()));
    public static final RegistryObject<Item> Gallium_Ore_Item = ITEMS.register("gallium_ore", () -> new BlockItemBase(Gallium_Ore.get()));
    public static final RegistryObject<Item> Hafnium_Ore_Item = ITEMS.register("hafnium_ore", () -> new BlockItemBase(Hafnium_Ore.get()));
    public static final RegistryObject<Item> Holmium_Ore_Item = ITEMS.register("holmium_ore", () -> new BlockItemBase(Holmium_Ore.get()));
    public static final RegistryObject<Item> Indium_Ore_Item = ITEMS.register("indium_ore", () -> new BlockItemBase(Indium_Ore.get()));
    public static final RegistryObject<Item> Iridium_Ore_Item = ITEMS.register("iridium_ore", () -> new BlockItemBase(Iridium_Ore.get()));
    public static final RegistryObject<Item> Lanthanum_Ore_Item = ITEMS.register("lanthanum_ore", () -> new BlockItemBase(Lanthanum_Ore.get()));
    public static final RegistryObject<Item> Lead_Ore_Item = ITEMS.register("lead_ore", () -> new BlockItemBase(Lead_Ore.get()));
    public static final RegistryObject<Item> Lithium_Ore_Item = ITEMS.register("lithium_ore", () -> new BlockItemBase(Lithium_Ore.get()));
    public static final RegistryObject<Item> Lutetium_Ore_Item = ITEMS.register("lutetium_ore", () -> new BlockItemBase(Lutetium_Ore.get()));
    public static final RegistryObject<Item> Magnesium_Ore_Item = ITEMS.register("magnesium_ore", () -> new BlockItemBase(Magnesium_Ore.get()));
    public static final RegistryObject<Item> Manganese_Ore_Item = ITEMS.register("manganese_ore", () -> new BlockItemBase(Manganese_Ore.get()));
    public static final RegistryObject<Item> Mendelevium_Ore_Item = ITEMS.register("mendelevium_ore", () -> new BlockItemBase(Mendelevium_Ore.get()));
    public static final RegistryObject<Item> Mercury_Ore_Item = ITEMS.register("mercury_ore", () -> new BlockItemBase(Mercury_Ore.get()));
    public static final RegistryObject<Item> Molybdenum_Ore_Item = ITEMS.register("molybdenum_ore", () -> new BlockItemBase(Molybdenum_Ore.get()));
    public static final RegistryObject<Item> Neodymium_Ore_Item = ITEMS.register("neodymium_ore", () -> new BlockItemBase(Neodymium_Ore.get()));
    public static final RegistryObject<Item> Nickel_Ore_Item = ITEMS.register("nickel_ore", () -> new BlockItemBase(Nickel_Ore.get()));
    public static final RegistryObject<Item> Niobium_Ore_Item = ITEMS.register("niobium_ore", () -> new BlockItemBase(Niobium_Ore.get()));
    public static final RegistryObject<Item> Osmium_Ore_Item = ITEMS.register("osmium_ore", () -> new BlockItemBase(Osmium_Ore.get()));
    public static final RegistryObject<Item> Palladium_Ore_Item = ITEMS.register("palladium_ore", () -> new BlockItemBase(Palladium_Ore.get()));
    public static final RegistryObject<Item> Platinium_Ore_Item = ITEMS.register("platinum_ore", () -> new BlockItemBase(Platinum_Ore.get()));
    public static final RegistryObject<Item> Polonium_Ore_Item = ITEMS.register("polonium_ore", () -> new BlockItemBase(Polonium_Ore.get()));
    public static final RegistryObject<Item> Potassium_Ore_Item = ITEMS.register("potassium_ore", () -> new BlockItemBase(Potassium_Ore.get()));
    public static final RegistryObject<Item> Praseodymium_Ore_Item = ITEMS.register("praseodymium_ore", () -> new BlockItemBase(Praseodymium_Ore.get()));
    public static final RegistryObject<Item> Protactinium_Ore_Item = ITEMS.register("protactinium_ore", () -> new BlockItemBase(Protactinium_Ore.get()));
    public static final RegistryObject<Item> Radium_Ore_Item = ITEMS.register("radium_ore", () -> new BlockItemBase(Radium_Ore.get()));
    public static final RegistryObject<Item> Rhenium_Ore_Item = ITEMS.register("rhenium_ore", () -> new BlockItemBase(Rhenium_Ore.get()));
    public static final RegistryObject<Item> Rhodium_Ore_Item = ITEMS.register("rhodium_ore", () -> new BlockItemBase(Rhodium_Ore.get()));
    public static final RegistryObject<Item> Rubidium_Ore_Item = ITEMS.register("rubidium_ore", () -> new BlockItemBase(Rubidium_Ore.get()));
    public static final RegistryObject<Item> Ruthenium_Ore_Item = ITEMS.register("ruthenium_ore", () -> new BlockItemBase(Ruthenium_Ore.get()));
    public static final RegistryObject<Item> Samarium_Ore_Item = ITEMS.register("samarium_ore", () -> new BlockItemBase(Samarium_Ore.get()));
    public static final RegistryObject<Item> Scandium_Ore_Item = ITEMS.register("scandium_ore", () -> new BlockItemBase(Scandium_Ore.get()));
    public static final RegistryObject<Item> Silicon_Ore_Item = ITEMS.register("silicon_ore", () -> new BlockItemBase(Silicon_Ore.get()));
    public static final RegistryObject<Item> Silver_Ore_Item = ITEMS.register("silver_ore", () -> new BlockItemBase(Silver_Ore.get()));
    public static final RegistryObject<Item> Sodium_Ore_Item = ITEMS.register("sodium_ore", () -> new BlockItemBase(Sodium_Ore.get()));
    public static final RegistryObject<Item> Strontium_Ore_Item = ITEMS.register("strontium_ore", () -> new BlockItemBase(Strontium_Ore.get()));
    public static final RegistryObject<Item> Tantalum_Ore_Item = ITEMS.register("tantalum_ore", () -> new BlockItemBase(Tantalum_Ore.get()));
    public static final RegistryObject<Item> Terbium_Ore_Item = ITEMS.register("terbium_ore", () -> new BlockItemBase(Terbium_Ore.get()));
    public static final RegistryObject<Item> Thallium_Ore_Item = ITEMS.register("thallium_ore", () -> new BlockItemBase(Thallium_Ore.get()));
    public static final RegistryObject<Item> Thorium_Ore_Item = ITEMS.register("thorium_ore", () -> new BlockItemBase(Thorium_Ore.get()));
    public static final RegistryObject<Item> Thulium_Ore_Item = ITEMS.register("thulium_ore", () -> new BlockItemBase(Thulium_Ore.get()));
    public static final RegistryObject<Item> Tin_Ore_Item = ITEMS.register("tin_ore", () -> new BlockItemBase(Tin_Ore.get()));
    public static final RegistryObject<Item> Titanium_Ore_Item = ITEMS.register("titanium_ore", () -> new BlockItemBase(Titanium_Ore.get()));
    public static final RegistryObject<Item> Tungsten_Ore_Item = ITEMS.register("tungsten_ore", () -> new BlockItemBase(Tungsten_Ore.get()));
    public static final RegistryObject<Item> Uranium_Ore_Item = ITEMS.register("uranium_ore", () -> new BlockItemBase(Uranium_Ore.get()));
    public static final RegistryObject<Item> Vanadium_Ore_Item = ITEMS.register("vanadium_ore", () -> new BlockItemBase(Vanadium_Ore.get()));
    public static final RegistryObject<Item> Ytterbium_Ore_Item = ITEMS.register("ytterbium_ore", () -> new BlockItemBase(Ytterbium_Ore.get()));
    public static final RegistryObject<Item> Yttrium_Ore_Item = ITEMS.register("yttrium_ore", () -> new BlockItemBase(Yttrium_Ore.get()));
    public static final RegistryObject<Item> Zinc_Ore_Item = ITEMS.register("zinc_ore", () -> new BlockItemBase(Zinc_Ore.get()));
    public static final RegistryObject<Item> ZirconiumOre_Item = ITEMS.register("zirconium_ore", () -> new BlockItemBase(Zirconium_Ore.get()));

    // Blocks
    public static final RegistryObject<Block> Actinium_Block = BLOCKS.register("actinium_block", ActiniumBlock:: new);

    // Blocks Items
    public static final RegistryObject<Item> Actinium_Block_Item = ITEMS.register("actinium_block", () -> new BlockItemBase(Actinium_Block.get()));

}